#! /bin/bash

xrandr --output DP-1 --set "Broadcast RGB" "Full" 

if [[ $(xrandr --listmonitors) == *"1920/527x1080/296+0+0"* ]]
then
	xrandr --output eDP-1 --off
else
	xrandr --output eDP-1 --set "Broadcast RGB" "Full"
fi

