#! /usr/bin/python


import subprocess as sp

deb = sp.getoutput('deborphan')

exclude =['gir1.2-gtop-2.0']

def remove(package):
    sp.getoutput('sudo apt remove {} --purge'.format(package))


for i in deb.split('\n'):
    i = i.strip()
    if i not in exclude:
        print("removing {}".format(i))
        remove(i)

	


