#! /home/voccer/python

import subprocess as sp
from get_active_id import get_active_id
from tqdm import tqdm 
import time

def kill_process(list_id):
    for i in tqdm(list_id):
        time.sleep(0.01)
        sp.getoutput('kill {}'.format(i))
def logout():
    time.sleep(0.5)
    # print('logout')
    sp.getoutput('/usr/bin/gnome-session-quit --force')
if __name__ == '__main__':
    list_id = get_active_id()
    kill_process(list_id)
    logout()
                    

