#! /home/voccer/python

import subprocess as sp
from get_active_id import get_active_id
from tqdm import tqdm 
import time

def kill_process(list_id):
    for i in tqdm(list_id):
        sp.getoutput('kill {}'.format(i))
def reboot():
    print('Starting reboot ...')
    time.sleep(2)
    sp.getoutput('/usr/sbin/reboot')
if __name__ == '__main__':
    list_id = get_active_id()
    kill_process(list_id)
    reboot()
                    

