#! /home/voccer/python

import subprocess as sp
from get_active_id import get_active_id
from tqdm import tqdm 
import time

def kill_process(list_id):
    for i in tqdm(list_id):
        time.sleep(0.02)
        sp.getoutput('kill {}'.format(i))
def reboot():
    time.sleep(0.1)
    sp.getoutput('/usr/sbin/reboot')
def umount():
    sp.getoutput('/home/voccer/execute/umount_all')
if __name__ == '__main__':
    list_id = get_active_id()
    # print(list_id)
    print("Kill Process")
    kill_process(list_id)
    print("Umount")
    umount()
    print("reboot")
    reboot()
                    

