#! /bin/bash

/home/voccer/execute/start_thunderbird &
/home/voccer/execute/check_monitor &

/home/voccer/execute/notify_birthday/execute &
/home/voccer/execute/start_conky &
/usr/bin/plank &

/home/voccer/execute/turnoff_touchpad_keyboard &

sleep 5
/home/voccer/execute/set_english_keyboard &
/home/voccer/execute/select_mic &
/usr/bin/crow &
/home/voccer/execute/update auto &
