#! /home/voccer/python

import subprocess as sp
import datetime
import sys
import os
import time

def check_log():
    if not os.path.exists('/home/voccer/execute/update_log'):
        return True
    try:
        with open('/home/voccer/execute/update_log') as f:
            log = f.read().split('\n')
        
       #print(log)
        last_date = log[-2].split('-')[-1][:2]
        
        if int(datetime.datetime.now().day) != int(last_date):
            return True
    except Exception as e:
        print(e)

    return False

def update():
    sp.run('sudo apt update', shell=True)
    sp.run('sudo apt upgrade -y', shell=True)
    sp.run('sudo apt autoremove -y --purge', shell=True)
    sp.run('sudo apt autoclean', shell=True)

def write_log():
    with open('/home/voccer/execute/update_log', 'a+') as f:
        f.write(str(datetime.datetime.now()) + '\n')

if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'auto':
        if check_log():
            time.sleep(500)
            update()
            write_log()
    else:
        update()


