#! /usr/bin/python

import subprocess as sp 

path = '/home/voccer/execute/internal_touchpad_keyboard'
list_input = sp.getoutput('xinput --list').split('\n')

has_mouse = False
has_keyboard = False

for i in list_input:
    if 'G102' in i:
        has_mouse = True
    if 'Usb Gaming' in i:
        has_keyboard = True

if has_mouse:
    sp.run("/bin/bash {}/{}".format(path, "turnoff_touchpad"), shell=True)
if has_keyboard:
    sp.run("/bin/bash {}/{}".format(path, "turnoff_keyboard"), shell=True)
    