#! /usr/bin/python

import subprocess as sp 

list_input = sp.getoutput('xinput --list').split('\n')

for i in list_input:
    if 'AT Translated' in i:
        id_keyboard = i.split('=')[1][:2].strip()
sp.run("xinput set-prop {} 'Device Enabled' 0".format(id_keyboard),shell=True)